from sqlalchemy import create_engine  # type: ignore[import]
from sqlalchemy.orm import sessionmaker, declarative_base    # type: ignore[import]
from dotenv import load_dotenv
import os

load_dotenv() # load_dotenv() is a function from the python-dotenv library that loads environment variables from a .env file into the environment. This allows us to keep sensitive information, such as database connection strings, out of our source code and instead store them in a separate .env file that can be easily managed and kept secure. By calling load_dotenv() at the beginning of our application, we ensure that all the environment variables defined in the .env file are available for use throughout our application.

engine = create_engine(os.getenv("DB_URL")) # create_engine() is a function from SQLAlchemy that creates a new SQLAlchemy engine instance. The engine is the starting point for any SQLAlchemy application and is responsible for managing the connection to the database. By passing os.getenv("DB_URL") as an argument, we are retrieving the database connection string from the environment variable DB_URL, which should be defined in our .env file. This allows us to easily configure our database connection without hardcoding sensitive information in our source code. The created engine will be used to interact with the database throughout our application.

db_session = sessionmaker(autocommit=False, autoflush=False, bind=engine) # sessionmaker() is a function from SQLAlchemy that creates a new session factory. A session factory is a callable that returns new Session objects when called. By setting autocommit=False, we are disabling the autocommit mode, which means that we will need to explicitly call db.commit() to save changes to the database. By setting autoflush=False, we are disabling the autoflush mode, which means that changes to the database will not be automatically flushed before queries are executed. Finally, by passing bind=engine, we are associating the session factory with the engine we created earlier, allowing us to use the session factory to interact with the database through that engine.

Base = declarative_base() # declarative_base() is a function from SQLAlchemy that returns a new base class for declarative class definitions. This base class is used to define our SQLAlchemy models, which represent the tables in our database. By creating a base class using declarative_base(), we can then define our models as subclasses of this base class, allowing us to easily map our Python classes to database tables and perform CRUD operations on the database using SQLAlchemy's ORM capabilities.

# Dependency to get a database session for each request
def get_db():
    db = db_session() # When get_db() is called, it creates a new database session by calling the db_session factory we defined earlier. This session will be used to interact with the database for the duration of the request. By using a dependency like this in our FastAPI endpoints, we can ensure that each request gets its own database session, which helps to manage database connections efficiently and avoid issues with concurrent requests sharing the same session. The session will be automatically closed after the request is completed, thanks to the use of a try-finally block in this function.
    try:
        yield db # The yield statement is used to create a generator function, which allows us to use this function as a dependency in our FastAPI endpoints. When an endpoint depends on get_db(), FastAPI will call this function to get a database session for the request. The code before the yield statement will be executed when the dependency is first called, and the code after the yield statement will be executed when the request is completed. This allows us to manage the lifecycle of the database session, ensuring that it is properly closed after the request is finished, even if an error occurs during the request processing.
    finally:
        db.close() # The finally block is used to ensure that the database session is closed after the request is completed, regardless of whether an error occurred or not. By calling db.close() in the finally block, we can guarantee that the database connection is properly released back to the connection pool, preventing potential issues with too many open connections or resource leaks in our application. This is an important aspect of managing database connections efficiently in a web application.